server:
  port: 8087
spring:
  application:
    name: filehandler-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    #    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/file_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
springdoc:
  swagger-ui:
    path: /swagger-ui